### PR TITLE
Add RabbitMQ VirtualHost parameter

### PR DESCRIPTION
**Pull request by Etienne-Carriere**

### CODE REVIEW

**Comment by Etienne-Carriere** [comment]
After the merge, would it be possible to publish a new version ?

**Comment by FrogDevelopper** [comment]
A will release the new version this evening

thanks again

**Comment by FrogDevelopper** [comment]
@Etienne-Carriere the version 1.3.0 is available

**Comment by jsuag** [comment]
How I can change the content_type of the rabbitmq message?

**Pull request merged**
